create extension if not exists pgcrypto;
create schema if not exists notai;

with services(slug, name, category, plain_name, intent, complexity, remote_possible, requires_in_person, synonyms) as (
    values
        ('acquisto-prima-casa', 'Acquisto prima casa', 'Atti Immobiliari', 'Acquisto prima casa', 'Comprare la prima casa e capire costo del notaio, imposte e documenti.', 'media', false, true, array['prima casa', 'rogito prima casa', 'comprare prima casa']),
        ('acquisto-seconda-casa', 'Acquisto seconda casa', 'Atti Immobiliari', 'Acquisto seconda casa', 'Comprare una seconda casa e stimare notaio, imposte e spese.', 'media', false, true, array['seconda casa', 'rogito seconda casa']),
        ('acquisto-casa-con-mutuo', 'Acquisto casa con mutuo', 'Atti Immobiliari', 'Acquisto casa con mutuo', 'Comprare casa con mutuo e ricevere preventivo per rogito e atto di mutuo.', 'media', false, true, array['rogito con mutuo', 'prima casa con mutuo', 'atto mutuo e compravendita']),
        ('preliminare-compravendita', 'Preliminare di compravendita', 'Atti Immobiliari', 'Compromesso casa', 'Registrare o stipulare un compromesso prima del rogito.', 'bassa', false, true, array['compromesso', 'preliminare casa', 'contratto preliminare']),
        ('trascrizione-preliminare', 'Trascrizione preliminare', 'Atti Immobiliari', 'Trascrizione compromesso', 'Trascrivere un preliminare nei registri immobiliari per tutelare lacquirente.', 'bassa', false, true, array['trascrizione compromesso', 'registrare compromesso notaio']),
        ('cancellazione-ipoteca', 'Cancellazione ipoteca', 'Atti Immobiliari', 'Cancellazione ipoteca', 'Cancellare una ipoteca o verificare la cancellazione collegata a mutuo estinto.', 'bassa', false, true, array['cancellare ipoteca', 'estinzione ipoteca']),
        ('vendita-terreno', 'Vendita terreno', 'Atti Immobiliari', 'Vendita terreno', 'Vendere o acquistare un terreno agricolo o edificabile.', 'media', false, true, array['acquisto terreno', 'rogito terreno']),
        ('vendita-box-garage', 'Vendita box o garage', 'Atti Immobiliari', 'Vendita box o garage', 'Acquistare o vendere box, garage o pertinenza.', 'bassa', false, true, array['acquisto box', 'rogito garage', 'compravendita box', 'vendita box', 'vendita garage', 'posto auto']),
        ('atto-di-riconoscimento-debito', 'Riconoscimento di debito', 'Atti notarili', 'Riconoscimento di debito', 'Formalizzare un debito o un accordo di pagamento con atto notarile.', 'bassa', false, true, array['riconoscimento debito', 'scrittura privata notarile']),
        ('scrittura-privata-autenticata', 'Scrittura privata autenticata', 'Atti notarili', 'Scrittura privata autenticata', 'Autenticare una scrittura privata per darle certezza e opponibilita.', 'bassa', false, true, array['scrittura privata', 'autentica scrittura privata']),
        ('copia-conforme', 'Copia conforme', 'Altri Servizi', 'Copia conforme', 'Ottenere una copia conforme di un documento o atto.', 'bassa', false, true, array['copie conformi', 'copia autentica']),
        ('autentica-copia', 'Autentica di copia', 'Altri Servizi', 'Autentica di copia', 'Autenticare una copia rispetto all’originale.', 'bassa', false, true, array['autenticazione copia', 'copia autentica']),
        ('traduzione-giurata', 'Traduzione giurata', 'Altri Servizi', 'Traduzione giurata', 'Giurare o asseverare una traduzione per uso legale o estero.', 'bassa', false, true, array['asseverazione traduzione', 'traduzione asseverata']),
        ('dichiarazione-sostitutiva-atto-notorieta', 'Dichiarazione sostitutiva atto di notorieta', 'Altri Servizi', 'Dichiarazione sostitutiva', 'Formalizzare una dichiarazione sostitutiva o atto notorio.', 'bassa', false, true, array['atto notorio', 'dichiarazione atto notorio']),
        ('pubblicazione-testamento-olografo', 'Pubblicazione testamento olografo', 'Diritto di Famiglia', 'Pubblicazione testamento olografo', 'Pubblicare un testamento olografo dopo il decesso.', 'bassa', false, true, array['pubblicazione testamento', 'testamento olografo']),
        ('deposito-testamento-olografo', 'Deposito testamento olografo', 'Diritto di Famiglia', 'Deposito testamento olografo', 'Depositare presso notaio un testamento scritto di proprio pugno.', 'bassa', false, true, array['depositare testamento', 'conservazione testamento']),
        ('rinuncia-eredita', 'Rinuncia all eredita', 'Diritto di Famiglia', 'Rinuncia eredità', 'Rinunciare alleredità davanti a notaio o cancelliere.', 'bassa', false, true, array['rinuncia eredità', 'rinunciare eredita']),
        ('accettazione-eredita', 'Accettazione eredita', 'Diritto di Famiglia', 'Accettazione eredità', 'Accettare una eredità, anche con trascrizione o beni immobili.', 'media', false, true, array['accettazione eredità', 'accettare eredita']),
        ('accettazione-beneficio-inventario', 'Accettazione con beneficio di inventario', 'Diritto di Famiglia', 'Beneficio di inventario', 'Accettare leredità limitando la responsabilità ai beni ereditari.', 'media', false, true, array['beneficio inventario', 'accettazione beneficiata']),
        ('inventario-eredita', 'Inventario eredita', 'Diritto di Famiglia', 'Inventario eredità', 'Redigere inventario dei beni ereditari.', 'media', false, true, array['inventario successione', 'inventario beni ereditari']),
        ('divisione-ereditaria', 'Divisione ereditaria', 'Diritto di Famiglia', 'Divisione ereditaria', 'Dividere beni ereditari tra eredi con atto notarile.', 'media', false, true, array['divisione eredita', 'scioglimento comunione ereditaria']),
        ('fondo-patrimoniale', 'Fondo patrimoniale', 'Diritto di Famiglia', 'Fondo patrimoniale', 'Costituire un fondo patrimoniale per destinare beni ai bisogni della famiglia.', 'media', false, true, array['costituzione fondo patrimoniale']),
        ('patto-di-famiglia', 'Patto di famiglia', 'Diritto di Famiglia', 'Patto di famiglia', 'Gestire passaggio generazionale di azienda o quote a discendenti.', 'alta', false, true, array['patti di famiglia', 'passaggio generazionale']),
        ('patti-convivenza', 'Contratto di convivenza', 'Diritto di Famiglia', 'Contratto di convivenza', 'Regolare rapporti patrimoniali tra conviventi.', 'bassa', false, true, array['patti convivenza', 'convivenza di fatto']),
        ('fondo-speciale-disabile', 'Trust o vincolo per disabile', 'Diritto di Famiglia', 'Vincolo per disabile', 'Destinare beni a tutela di una persona con disabilità o fragile.', 'alta', false, true, array['dopo di noi', 'vincolo destinazione disabile', 'trust disabile']),
        ('verbale-assemblea', 'Verbale assemblea societaria', 'Diritto Societario', 'Verbale assemblea', 'Verbalizzare assemblea societaria davanti al notaio.', 'media', false, true, array['verbale assemblea straordinaria']),
        ('aumento-capitale', 'Aumento di capitale', 'Diritto Societario', 'Aumento capitale', 'Deliberare aumento di capitale sociale.', 'media', false, true, array['aumento capitale srl', 'aumento capitale spa']),
        ('riduzione-capitale', 'Riduzione di capitale', 'Diritto Societario', 'Riduzione capitale', 'Deliberare riduzione capitale sociale.', 'media', false, true, array['riduzione capitale srl']),
        ('trasformazione-societaria', 'Trasformazione societaria', 'Diritto Societario', 'Trasformazione società', 'Trasformare una societa in altro tipo societario.', 'media', false, true, array['trasformazione srl spa', 'trasformazione societa']),
        ('liquidazione-societa', 'Liquidazione societa', 'Diritto Societario', 'Liquidazione società', 'Avviare o verbalizzare liquidazione societaria.', 'media', false, true, array['messa in liquidazione']),
        ('cessione-azienda', 'Cessione azienda', 'Diritto Societario', 'Cessione azienda', 'Vendere o acquistare azienda o ramo dazienda.', 'alta', false, true, array['vendita azienda', 'cessione ramo azienda']),
        ('affitto-azienda', 'Affitto azienda', 'Diritto Societario', 'Affitto azienda', 'Stipulare contratto di affitto dazienda o ramo dazienda.', 'media', false, true, array['affitto ramo azienda']),
        ('atto-costitutivo-associazione', 'Costituzione associazione', 'Enti e no profit', 'Costituzione associazione', 'Costituire associazione, fondazione o ente non profit con atto notarile.', 'media', false, true, array['atto costitutivo associazione', 'costituzione fondazione']),
        ('costituzione-cooperativa', 'Costituzione cooperativa', 'Diritto Societario', 'Costituzione cooperativa', 'Costituire societa cooperativa.', 'media', false, true, array['aprire cooperativa']),
        ('vidimazione-libri-sociali', 'Vidimazione libri sociali', 'Diritto Societario', 'Vidimazione libri sociali', 'Vidimare libri sociali o registri quando richiesto.', 'bassa', false, true, array['vidimare libro soci', 'vidimazione registri'])
)
insert into notai.services_taxonomy (
    slug,
    name,
    category,
    plain_language_name,
    user_intent,
    seo_title,
    seo_description,
    service_scope,
    standardizable,
    remote_possible,
    requires_in_person,
    complexity,
    synonyms,
    priority
)
select
    slug,
    name,
    category,
    plain_name,
    intent,
    initcap(plain_name) || ': costo, documenti e preventivo notaio',
    'Guida a ' || lower(plain_name) || ': quando serve, documenti richiesti, costo indicativo e richiesta preventivo ai notai disponibili.',
    'notarial',
    true,
    remote_possible,
    requires_in_person,
    complexity,
    synonyms,
    80
from services
on conflict (slug) do update set
    name = excluded.name,
    category = excluded.category,
    plain_language_name = excluded.plain_language_name,
    user_intent = excluded.user_intent,
    seo_title = excluded.seo_title,
    seo_description = excluded.seo_description,
    remote_possible = excluded.remote_possible,
    requires_in_person = excluded.requires_in_person,
    complexity = excluded.complexity,
    synonyms = excluded.synonyms,
    priority = least(notai.services_taxonomy.priority, excluded.priority);

with seed(slug, min_eur, avg_eur, max_eur, confidence, evidence, notes, source_urls) as (
    values
        ('acquisto-prima-casa', 1500, 2250, 3000, 0.600, 'Range coerente con rogito prima casa; fonti pubbliche riportano spesso 1.500-3.000 euro con variabilita per imposte e valore.', 'Comprende stima indicativa pratica; imposte e valore catastale sono variabili.', array['https://www.mutuionline.it/guide-mutui/domande-frequenti/quali-sono-i-costi-del-notaio-quando-si-compra-casa.asp','https://www.euroansa.it/guide/domande-frequenti/quanto-costa-il-notaio-per-acquisto-casa-con-mutuo']),
        ('acquisto-seconda-casa', 1800, 3000, 5500, 0.480, 'Seconda casa spesso piu onerosa per imposte; onorario e spese dipendono dal valore.', 'Stima complessiva indicativa; imposte escluse dal benchmark professionale ma rilevanti nel totale utente.', array['https://www.bancobpm.it/magazine/privati/realizza-i-tuoi-progetti/acquisto-prima-casa-come-calcolare-il-preventivo-del-notaio/']),
        ('acquisto-casa-con-mutuo', 2500, 3500, 4500, 0.560, 'AI overview e fonti mutui riportano acquisto con mutuo spesso 2.500-4.500 euro per due atti distinti.', 'Compravendita + mutuo; imposte e spese bancarie variabili.', array['https://www.euroansa.it/guide/domande-frequenti/quanto-costa-il-notaio-per-acquisto-casa-con-mutuo','https://www.mutuionline.it/guide-mutui/domande-frequenti/quali-sono-i-costi-del-notaio-quando-si-compra-casa.asp']),
        ('preliminare-compravendita', 600, 900, 1300, 0.520, 'Casavo e Quotalo indicano registrazione preliminare da notaio mediamente 800-1.000 euro; imposta registro fissa 200 euro piu bolli/acconti.', 'Preliminare/compromesso; non sostituisce rogito.', array['https://casavo.com/it/guide/come-comprare-casa/contratto-preliminare-come-funziona-chi-lo-paga-e-quanto-costa/','https://www.quotalo.it/guide/l-atto-di-trascrizione-di-un-preliminare-e-obbligatorio-e-quanto-costa','https://www.notaiofacile.it/blog/quanto-costa-registrare-e-trascrivere-un-compromesso.html']),
        ('trascrizione-preliminare', 800, 1100, 1800, 0.520, 'NotaioTorino indica imposte fisse per trascrizione preliminare: registro 200, ipotecaria 200, tributi 35, oltre onorario; Quotalo/Casavo riportano 800-1.000 euro medi.', 'Protezione acquirente; costi vivi e onorario separabili.', array['https://www.notaiotorino.org/attivita-dello-studio/settore-immobiliare/contratto-preliminare/','https://www.quotalo.it/guide/l-atto-di-trascrizione-di-un-preliminare-e-obbligatorio-e-quanto-costa']),
        ('cancellazione-ipoteca', 200, 500, 1000, 0.360, 'Pratica spesso standard, ma dipende da tipo ipoteca e adempimenti.', 'Range preliminare da validare con preventivi reali.', array['https://www.notariato.it/it/casa/']),
        ('vendita-terreno', 1200, 2300, 5000, 0.430, 'Atto immobiliare con complessita urbanistica/catastale variabile.', 'Certificato destinazione urbanistica e imposte incidono molto.', array['https://www.notariato.it/it/casa/']),
        ('vendita-box-garage', 700, 1200, 2500, 0.420, 'Trasferimento immobiliare piu semplice e di valore spesso inferiore rispetto ad abitazione.', 'Se pertinenza di prima casa cambiano imposte.', array['https://www.notariato.it/it/casa/']),
        ('atto-di-riconoscimento-debito', 300, 700, 1500, 0.360, 'Atto relativamente standard ma dipendente da importo e garanzie.', 'Stima iniziale.', array['https://www.notariato.it/it/']),
        ('scrittura-privata-autenticata', 150, 400, 1000, 0.420, 'Autentica notarile di scrittura privata con complessita variabile.', 'Dipende da documento, parti e imposte.', array['https://www.notariato.it/it/']),
        ('copia-conforme', 30, 80, 200, 0.360, 'Servizio documentale semplice.', 'Prezzo dipende da numero pagine e urgenza.', array['https://www.notariato.it/it/']),
        ('autentica-copia', 30, 80, 200, 0.360, 'Servizio documentale semplice.', 'Prezzo dipende da numero copie.', array['https://www.notariato.it/it/']),
        ('traduzione-giurata', 80, 180, 500, 0.340, 'Asseverazioni/legalizzazioni variano per lingua e lunghezza documento.', 'Traduttore eventualmente escluso.', array['https://www.notariato.it/it/']),
        ('dichiarazione-sostitutiva-atto-notorieta', 80, 180, 400, 0.380, 'Atto dichiarativo standard.', 'Può richiedere testimoni/documenti.', array['https://www.notariato.it/it/']),
        ('pubblicazione-testamento-olografo', 400, 800, 1500, 0.500, 'Officina Notarile indica imposta bollo 45 euro e registro 200 euro per pubblicazione testamento olografo; costi maggiori se ci sono dichiarazioni ulteriori.', 'Tasse fisse incluse solo come evidenza, prezzo finale variabile.', array['https://www.officinanotarile.it/pubblicazionetestamentoolografo/']),
        ('deposito-testamento-olografo', 150, 350, 800, 0.390, 'Deposito/conservazione testamento semplice rispetto a pubblicazione.', 'Stima iniziale.', array['https://www.notariato.it/it/famiglia/']),
        ('rinuncia-eredita', 250, 500, 1000, 0.470, 'Fonti legali indicano imposta registro 200 euro piu bolli/costi; notaio o cancelliere.', 'Onorario variabile, alternativa tribunale possibile.', array['https://www.studiolegalecastello.it/la-rinuncia-alleredita/']),
        ('accettazione-eredita', 1000, 1750, 3000, 0.470, 'deQuo riporta onorario notarile indicativo 1.500-2.000 euro per accettazione eredita, oltre bolli/oneri.', 'Dipende da immobili e trascrizioni.', array['https://www.dequo.it/articoli/accettazione-eredita-termine-costi']),
        ('accettazione-beneficio-inventario', 1500, 2200, 4000, 0.470, 'Brocardi riporta onorario circa 2.000 euro oltre costi fissi, trascrizione e bolli per accettazione beneficiata.', 'Procedura complessa e variabile.', array['https://www.brocardi.it/notizie-giuridiche/quanto-costa-accettazione-dell-eredita-ecco-come-fare-senza-notaio/3462.html']),
        ('inventario-eredita', 800, 1500, 3000, 0.400, 'Inventario collegato a beneficio di inventario; costi dipendono da patrimonio e beni.', 'Stima iniziale.', array['https://www.brocardi.it/notizie-giuridiche/quanto-costa-accettazione-dell-eredita-ecco-come-fare-senza-notaio/3462.html']),
        ('divisione-ereditaria', 1200, 2500, 6000, 0.440, 'Divisione tra eredi simile a divisione immobiliare, con variabilita su beni e conguagli.', 'Imposte e numero beni incidono molto.', array['https://www.notariato.it/it/famiglia/']),
        ('fondo-patrimoniale', 800, 1600, 3500, 0.430, 'NotaioFacile ribadisce assenza di tariffario; Officina Notarile elenca imposte e tributi in caso di beni immobili.', 'Molto variabile se conferisce immobili.', array['https://www.notaiofacile.it/contenuti/quanto-costa-costituire-un-fondo-patrimoniale.html','https://www.officinanotarile.it/fondopatrimoniale/','https://www.notariato.it/it/famiglia/fondo-patrimoniale/']),
        ('patto-di-famiglia', 2000, 4500, 10000, 0.360, 'Atto complesso di passaggio generazionale; NotaioFacile chiarisce natura gratuita e trattamento fiscale specifico.', 'Richiede analisi azienda/quote e partecipazione legittimari.', array['https://www.notaiofacile.it/contenuti/patto-di-famiglia.html','https://www.tonalini.it/pasgen/pattofam.html']),
        ('patti-convivenza', 400, 800, 1800, 0.360, 'Contratto familiare/patrimoniale relativamente standard.', 'Variabile se include beni o trasferimenti.', array['https://www.notariato.it/it/famiglia/']),
        ('fondo-speciale-disabile', 1500, 3500, 8000, 0.320, 'Atti di destinazione/trust per soggetti fragili sono complessi e personalizzati.', 'Necessario preventivo su misura.', array['https://www.notariato.it/it/famiglia/']),
        ('verbale-assemblea', 700, 1300, 2500, 0.420, 'Verbale societario standard, variabile per societa e delibera.', 'Stima iniziale.', array['https://www.notariato.it/it/impresa/']),
        ('aumento-capitale', 1000, 1800, 4000, 0.420, 'Delibera societaria con adempimenti notarili e registrali.', 'Dipende da importo e societa.', array['https://www.notariato.it/it/impresa/']),
        ('riduzione-capitale', 1000, 1800, 4000, 0.400, 'Delibera societaria con complessita simile ad aumento capitale.', 'Dipende da motivo e adempimenti.', array['https://www.notariato.it/it/impresa/']),
        ('trasformazione-societaria', 1200, 2200, 5000, 0.400, 'Operazione societaria straordinaria, variabile per perizie e assetto.', 'Stima iniziale.', array['https://www.notariato.it/it/impresa/']),
        ('liquidazione-societa', 900, 1600, 3500, 0.380, 'Atto/delibera societaria variabile per societa e stato patrimoniale.', 'Stima iniziale.', array['https://www.notariato.it/it/impresa/']),
        ('cessione-azienda', 1500, 3000, 8000, 0.360, 'Atto complesso su azienda/ramo, con verifiche e valore variabile.', 'Richiede valutazione caso.', array['https://www.notariato.it/it/impresa/']),
        ('affitto-azienda', 900, 1800, 4500, 0.360, 'Contratto su azienda o ramo con complessita patrimoniale variabile.', 'Stima iniziale.', array['https://www.notariato.it/it/impresa/']),
        ('atto-costitutivo-associazione', 600, 1200, 2500, 0.390, 'Costituzione ente/no profit, variabile per statuto e natura ente.', 'Stima iniziale.', array['https://www.notariato.it/it/']),
        ('costituzione-cooperativa', 1200, 2200, 4500, 0.390, 'Costituzione societaria specifica con statuto e adempimenti.', 'Stima iniziale.', array['https://www.notariato.it/it/impresa/']),
        ('vidimazione-libri-sociali', 80, 180, 500, 0.340, 'Servizio documentale/societario semplice.', 'Dipende da numero registri.', array['https://www.notariato.it/it/impresa/'])
)
insert into notai.service_price_benchmarks (
    service_id,
    location_scope,
    price_min_cents,
    price_avg_cents,
    price_max_cents,
    currency,
    sample_size,
    source,
    confidence,
    evidence,
    payload,
    valid_from
)
select
    st.id,
    'national',
    seed.min_eur * 100,
    seed.avg_eur * 100,
    seed.max_eur * 100,
    'EUR',
    0,
    'public_web_expanded_seed_2026',
    seed.confidence,
    seed.evidence,
    jsonb_build_object(
        'notes', seed.notes,
        'includes_taxes', false,
        'includes_professional_fee', true,
        'is_official_tariff', false,
        'needs_case_specific_quote', true,
        'source_urls', to_jsonb(seed.source_urls)
    ),
    date '2026-08-13'
from seed
join notai.services_taxonomy st on st.slug = seed.slug
on conflict (service_id, location_scope, coalesce(comune, ''), coalesce(province, ''), coalesce(region, ''), source, valid_from)
do update set
    price_min_cents = excluded.price_min_cents,
    price_avg_cents = excluded.price_avg_cents,
    price_max_cents = excluded.price_max_cents,
    confidence = excluded.confidence,
    evidence = excluded.evidence,
    payload = excluded.payload,
    updated_at = now();
